### ISSUE TITLE
Error: No whitespace between attributes

### ISSUE THREAD

**Issue by TimotheEmber** [amansx/alexa-raspberry#3]
Hi wen i ask alexa to find devices it does not find any and I get the following error in console:

pi@asconaberry:~/rpi-WeMo $ alexa-raspberry devices.json
Loading config file: '/home/pi/rpi-WeMo/devices.json'
Desk Light Now online, Now listening on 9000
Error: No whitespace between attributes
Line: 0
Column: 102
Char: s
    at error (/usr/local/lib/node_modules/alexa-raspberry/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/usr/local/lib/node_modules/alexa-raspberry/node_modules/sax/lib/sax.js:677:7)
    at SAXParser.write (/usr/local/lib/node_modules/alexa-raspberry/node_modules/sax/lib/sax.js:1395:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/alexa-raspberry/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/local/lib/node_modules/alexa-raspberry/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/usr/local/lib/node_modules/alexa-raspberry/node_modules/xml2js/lib/parser.js:369:19)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/alexa-raspberry/node_modules/wemore/lib/emulate.js:241:13)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Thank you

Tim

**Comment by ghost** [comment]
Same problem
